// Generated by CoffeeScript 1.6.3
module.exports = function(grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        "string-replace": {
            dev: {
                files: {
                    'dist/abn_tree_directive.js': 'src/abn_tree_directive.js'
                },
                options: {
                    replacements: [
                        {
                            pattern: "{html}",
                            replacement: function(match, p1, offset, string) {
                                return grunt.file.read('src/_template.html');
                            }
                        }
                    ]
                }
            }
        },
        watch: {
            css: {
                files: ['**/*.css'],
                tasks: [],
                options: {
                    livereload: true
                }
            }
        }
    });

    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-string-replace');

    grunt.registerTask('default', [
        'string-replace',
        'watch'
    ]);
};
